sudo: false
language: node_js
env:
  - PUBLISH_FROM_NODE_VERSION=8.0
node_js:
  - "6.0"
  - "8.0"
  - "node"
before_script:
  - npm list || true
  - rm -r node_modules/webpack && mkdir t-webpack && npm install --prefix t-webpack webpack && (npm list --prefix t-webpack || echo NPM LIST FAILED) && mv t-webpack/node_modules/webpack ./node_modules/ && rm -r t-webpack/
  - npm list || true
  - npm run build:browser
after_success:
  - ./.travis_publish
cache:
  directories:
    - node_modules
